### ISSUE TITLE
Batcher not Working in Proceswire 3.x

### ISSUE THREAD

**Issue by Broxden** [wanze/ProcessBatcher#3]
Batcher does not appear to work in Processwire 3.0.x. The Actions... link does not work.

**Comment by M-O-Z-G** [comment]
There's no problem with Batcher. PW3 haven't built-in Fancybox module. I had installed FancyBox from PW2 branch manually, and Butcher works now.

**Comment by wanze** [comment]
Hi,
Batcher needs an update in general :) I'm working on a new version which uses native ProcessWire modals and makes use of features like InputfieldSelector and findMany().

**Comment by eelke** [comment]
@wanze, Any updates on the new version? I used Batcher a lot (thank you!) and would love to have it in the current (stable) PW.    
[Meta: Imho I think this issue should not be a closed issue Batcher works with 3.x].
